# Generated by Django 4.0 on 2021-12-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='if_active',
            field=models.BooleanField(default=True),
        ),
    ]
