# Generated by Django 4.0 on 2021-12-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_post_if_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='date_on_new_work',
            field=models.DateField(auto_now=True),
        ),
    ]
