# Generated by Django 4.0 on 2021-12-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_employer_date_on_new_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='date_on_new_work',
            new_name='date_new_employment',
        ),
    ]
